# Simple workflow for deploying static content to GitHub Pages
name: Unit tests

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  # Single deploy job since we're just deploying
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Tests
        run: npm run test:unit
      - name: Build
        run: npm run build
